services:
  - type: web
    name: screen-recorder
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: true
    autoDeploy: true
    rootDir: .
    repo: https://github.com/yourusername/screenrecord-system
    branch: main
